CC = gcc

TARGET := test_SmartHomeSwitch

TESTSRC := ./utest_smartswitch.c
SRC     := ./smartswitch.c ../misc/str.c
MOKSRC  := ./mok/mok_smartswitch.c

include ../utest_makefile.common

prerun:
	@echo "No actions"
